// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwCUtmOrBWepetGuRXIcwOS25GrgpZqnw',
    appId: '1:421355697273:web:76724abeb1421344c850a8',
    messagingSenderId: '421355697273',
    projectId: 'hellofarmer-b820e',
    authDomain: 'hellofarmer-b820e.firebaseapp.com',
    storageBucket: 'hellofarmer-b820e.firebasestorage.app',
    measurementId: 'G-LGQKVHSGDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1WH-emXwiIiYW_AhKiiV2kl9ejgVn8WE',
    appId: '1:421355697273:android:0b9862b387c6564ec850a8',
    messagingSenderId: '421355697273',
    projectId: 'hellofarmer-b820e',
    storageBucket: 'hellofarmer-b820e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTuU-h0P_dg1gJM8xf_ZlwUbgmam95ot4',
    appId: '1:421355697273:ios:c186a4e4cd651ca4c850a8',
    messagingSenderId: '421355697273',
    projectId: 'hellofarmer-b820e',
    storageBucket: 'hellofarmer-b820e.firebasestorage.app',
    androidClientId: '421355697273-3n12alb4qbs93neb3l2tufolq8pds2mr.apps.googleusercontent.com',
    iosClientId: '421355697273-4ogorfjgtko0s53kog50blfijghv1t6h.apps.googleusercontent.com',
    iosBundleId: 'com.hellofarmer.helloFarmer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTuU-h0P_dg1gJM8xf_ZlwUbgmam95ot4',
    appId: '1:421355697273:ios:c186a4e4cd651ca4c850a8',
    messagingSenderId: '421355697273',
    projectId: 'hellofarmer-b820e',
    storageBucket: 'hellofarmer-b820e.firebasestorage.app',
    androidClientId: '421355697273-3n12alb4qbs93neb3l2tufolq8pds2mr.apps.googleusercontent.com',
    iosClientId: '421355697273-4ogorfjgtko0s53kog50blfijghv1t6h.apps.googleusercontent.com',
    iosBundleId: 'com.hellofarmer.helloFarmer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwCUtmOrBWepetGuRXIcwOS25GrgpZqnw',
    appId: '1:421355697273:web:64f3d56445870172c850a8',
    messagingSenderId: '421355697273',
    projectId: 'hellofarmer-b820e',
    authDomain: 'hellofarmer-b820e.firebaseapp.com',
    storageBucket: 'hellofarmer-b820e.firebasestorage.app',
    measurementId: 'G-Z5HTHFLFHH',
  );

}